# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TextDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextDemo

    # Networking
    pod 'Alamofire'
    pod 'Moya' #,:inhibit_warnings => true  # 消除警告
    pod 'Kingfisher'
    pod 'SwiftyJSON'
    pod 'HandyJSON'

    # Rx
    pod 'RxSwift'         
    pod 'RxCocoa'
    pod 'RxDataSources'

    # UI
    pod 'SnapKit'
    pod 'MJRefresh'
    pod 'SwiftMessages'
    pod 'FSPagerView'   #banner滚动图片
    pod 'DNSPageView'   # 分页
    pod 'JXMarqueeView' #跑马灯
    pod 'LTScrollView'  #滚动页
    pod 'TYCyclePagerView'
    pod 'TYPagerController'
	
    # Tools
    pod 'RTRootNavigationController'
    pod 'IQKeyboardManagerSwift'
    pod 'SVProgressHUD'
    pod 'MBProgressHUD'
    pod 'KeychainAccess', '3.1.0'  #钥匙链密码存储
    pod 'Then'
    pod 'ReusableKit'
    pod 'SwiftyColor'

  target 'TextDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
